function [ DataStruct ] = initHiPassFilter(maxFrameLength )
DataStruct = struct('maxFrameLength', maxFrameLength,...
                    'cachedMeasures' , zeros(3,maxFrameLength),...
                    'previousMean', 0,...
                    'previousFrameLength', 0,...
                    'frameLength', 0,...
                    'index', 1);


end

